name: Flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2

    - name: Set up Python 3.12
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      run: pip install flake8

    - name: Run Flake8
      run: flake8 energyplus_regressions
