name: Flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Pip Dependencies
      run: pip install flake8

    - name: Run Flake8
      run: flake8 energyplus_regressions
