name: Run Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ windows-latest, macos-11, ubuntu-22.04 ]  # macos-12 is not playing well with Tk
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v2
      - name: Set up Python 3.12
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: 3.12
      - name: Install Pip Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: coverage run -m pytest && coverage report
      - name: Coveralls
        # if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
